---
title: Midwest Medicare Plans
timezone: UTC
collections:
  drafts:
    title: Drafts
    output: false
  plans:
    title: Plans
    output: true
    permalink: "/plans/:path/"
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/services/:path/"
  team:
    title: Team
    output: true
    permalink: "/team/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: plans
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: ''
    type: services
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: images
  values:
    image: true
baseurl: 
exclude:
- ".sass-cache"
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
permalink: pretty
sass:
  style: compact
google_analytics_id: 
plugins:
- jekyll-environment-variables
page_descriptions:
  index: Our business assists clients with knowledge and understanding of insurance
    plans (risk transfer products) for out of pocket costs of their healthcare services.<br
    /><br />We offer advice on&colon;
  services: As an independent, licensed, Medicare insurance plan agent/broker, my
    business assists clients with knowledge and understanding of all insurance plan
    options. This includes Medicare Supplement policies, Medicare Advantage Prescription
    Drug plans, and Part D Prescription Drug Plans for your out of pocket health-care
    and prescription costs. In addition for you I give advice on Dental, Vision, and
    Hearing insurance plans, as well as enrolling you if requested. I offer to review
    all your insurance needs. This would include considering your age, health status,
    and retirement income available to use. Then I recommend the best value plan with
    the most benefit for the cost of premiums spent. In the future I will continue
    watching out for insurance changes which would affect you. In addition you will
    be comfortable you have checked another box toward gathering peace of mind in
    retirement.
  plans: 
  about: 
