---
title: Senior Medicare Plans
timezone: UTC
collections:
  plans:
    title: Plans
    output: true
    permalink: "/plans/:path/"
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/services/:path/"
  team:
    title: Team
    output: true
    permalink: "/team/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: plans
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: ''
    type: services
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: images
  values:
    image: true
baseurl: ""
exclude:
- .sass-cache
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
permalink: pretty
sass:
  style: compact
google_analytics_id:
plugins:
- jekyll-environment-variables
